Homework#2 - completed
Wizzard008/VladimirRyzhenkovMobile pull request #2
Opened 2021-08-03 00:03 UTC by Wizzard008

2021-08-11 18:33 UTC, MaksimMeshcheriakovEPAM requested changes
Поскольку есть существенное замечание - ложноположительный тест (см. в коде ПР), работа нуждается в доработке.
Остальные замечания некритичны.

2021-08-11 18:33 UTC, MaksimMeshcheriakovEPAM commented on src/test/java/scenarios/webMobileTests.java
> +        assert getPo().getWelement("searchResults").isDisplayed() : "No results displayed";
Вообще-то это ложноположительный тест: ведь практически по любой комбинации символов Гугл что-нибудь да найдет. Т.о. что-то да будет isDisplayed в любом случае.
Добавочно надо например валидировать, что найденные результаты действительно имеют какое-то отношение к ЕПАМ - ну хотя бы это слово содержат

2021-08-11 18:33 UTC, MaksimMeshcheriakovEPAM commented on src/main/resources/qa.properties
> +username=TestUserName
Лучше бы данные для разных типов тестов (в нашем случае - web и native) держать в разных файлов. Здесь данных и тестов мало, а вот если их будут сотни - запутаетесь держать в одном файле. Ну или хотя бы структурировать внутри файла - для .properties это секции [], а для действительно сложных проетков и структур данных лучше json, xml, yaml и т.п.

2021-08-11 18:33 UTC, MaksimMeshcheriakovEPAM commented on src/main/java/pageObjects/NativePageObject.java
>      @AndroidFindBy(id = "platkovsky.alexey.epamtestapp:id/email_sign_in_button")
Вообще лучше бы иметь по отдельному page object на каждый уникальный экран - например для страницы логина и регистрации и для страницы бюджета. А то будет легко запутаться по мере развития структуры page object

2021-08-11 22:30 UTC, Wizzard008 commented on src/main/resources/qa.properties
> +username=TestUserName
Разделил на два файла qaWeb и qaNative.

2021-08-11 22:32 UTC, Wizzard008 commented on src/main/java/pageObjects/NativePageObject.java
>      @AndroidFindBy(id = "platkovsky.alexey.epamtestapp:id/email_sign_in_button")
Разбил native тест на три страницы: LoginPage, RegistrationPage, BudgetPage.
Разбил web тест на две страницы: GoogleSearchWebPage, GoogleResultsWebPage.

2021-08-11 22:33 UTC, Wizzard008 commented on src/test/java/scenarios/webMobileTests.java
> +        assert getPo().getWelement("searchResults").isDisplayed() : "No results displayed";
Добавил проверку наличия текста EPAM в результатах поиска.

2021-08-25 13:58 UTC, MaksimMeshcheriakovEPAM approved these changes
Исправления приняты, работа зачтена.
Только пожалуй одно замечаните: данные лучше все же не зачитывать прямо в тело тестов, а передавать через параметры. А передаваемые значения считывать с помощью DataProvider (в случае использования TestNG)

2021-08-25 19:26 UTC, merged